- import_tasks: network.yml
- import_tasks: ca.yml
- import_tasks: packages.yml
- import_tasks: ldap.yml

- name: Configurar timezone
  timezone:
    name: America/Santarem

- name: Garantir hostname
  hostname:
    name: auth
