---
- name: Garantir sssd
  apt:
    name: 
      - sssd
      - libnss-sss
      - libpam-sss
    state: present

- name: Copiar a configuração do sssd.conf
  template:
    src: 20-sssd.conf.j2
    dest: /etc/sssd/conf.d/sssd.conf
    owner: root
    group: root
    mode: "0600"
