---
- name: Atualizar cache APT
  apt:
    update_cache: true

- name: Instalar pacotes base
  apt:
    name:
      - vim
      - wget
      - curl
      - sudo
      - rsync
      - bash-completion
      - dnsutils
      - netplan.io
      - tree
    state: present
