---
- name: Instalar squid
  apt:
    name: squid
    state: present

- name: Configurar squid
  template:
    src: squid.conf.j2
    dest: /etc/squid/squid.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart squid

- name: Habilitar squid
  service:
    name: squid
    enabled: true
    state: started

